# Permalinks
#

# Setup
title:               Kaizen
tagline:             'A story by Pliyo in the outter space'
description:         'A new era has begun'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            2
paginate_path:       "/blog/page:num/"

# Custom vars
version:             1.0.0
