# Permalinks
#

# Setup
title:               Pliyo's Spaceship
tagline:             'Itn the pursuit of the summer'
description:         'A new era has begun'
baseurl:             ''
paginate:            2
paginate_path:       "/blog/page:num/"

# Custom vars
version:             1.0.0
