# Permalinks
#

# Setup
title:               Pliyo's Spaceship
tagline:             'In the pursuit of the summer'
description:         'A new era has begun'
baseurl:             ''
url:                 'pliyosan.com'
paginate:            2
paginate_path:       "/blog/page:num/"

# Custom vars
version:             1.0.0
github:              https://github.com/pliyosenpai
twitter:             https://twitter.com/PliyoSan
instagram:           https://www.instagram.com/pliyosan/
linkedin:            https://uk.linkedin.com/in/pliyo

# Gems
gems:
  - jemoji
