# Permalinks
#

# Setup
title:               The Pursuit of the Summer
tagline:             'A story by PliyoSenpai'
description:         'A new era has begun'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            2
paginate_path:       "/blog/page:num/"

# Custom vars
version:             1.0.0
